# Generated by Django 3.1.4 on 2020-12-04 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=500)),
                ('price', models.PositiveSmallIntegerField()),
                ('color', models.CharField(max_length=50)),
                ('sold_out', models.BooleanField(default=False)),
                ('likes', models.IntegerField(blank=True, default=0)),
                ('photos', models.ImageField(blank=True, default='', upload_to='Products/img')),
                ('user', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='product', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
